//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTerminaldeServiciosPQR.ServiceReferencePQR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosSuscriptor", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioWebPQR")]
    [System.SerializableAttribute()]
    public partial class DatosSuscriptor : WPFTerminaldeServiciosPQR.ServiceReferencePQR.BaseRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nuFacturasconSaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long nuIdCuentaCobroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long nuIdSuscriptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nuSaldoPendienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nuSaldoPendienteAcuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nuSaldoPendienteAlcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nuSaldoPendienteUltimaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nuSaldoPteFinanciacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vaDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vaNombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nuFacturasconSaldo {
            get {
                return this.nuFacturasconSaldoField;
            }
            set {
                if ((this.nuFacturasconSaldoField.Equals(value) != true)) {
                    this.nuFacturasconSaldoField = value;
                    this.RaisePropertyChanged("nuFacturasconSaldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long nuIdCuentaCobro {
            get {
                return this.nuIdCuentaCobroField;
            }
            set {
                if ((this.nuIdCuentaCobroField.Equals(value) != true)) {
                    this.nuIdCuentaCobroField = value;
                    this.RaisePropertyChanged("nuIdCuentaCobro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long nuIdSuscriptor {
            get {
                return this.nuIdSuscriptorField;
            }
            set {
                if ((this.nuIdSuscriptorField.Equals(value) != true)) {
                    this.nuIdSuscriptorField = value;
                    this.RaisePropertyChanged("nuIdSuscriptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nuSaldoPendiente {
            get {
                return this.nuSaldoPendienteField;
            }
            set {
                if ((this.nuSaldoPendienteField.Equals(value) != true)) {
                    this.nuSaldoPendienteField = value;
                    this.RaisePropertyChanged("nuSaldoPendiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nuSaldoPendienteAcu {
            get {
                return this.nuSaldoPendienteAcuField;
            }
            set {
                if ((this.nuSaldoPendienteAcuField.Equals(value) != true)) {
                    this.nuSaldoPendienteAcuField = value;
                    this.RaisePropertyChanged("nuSaldoPendienteAcu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nuSaldoPendienteAlc {
            get {
                return this.nuSaldoPendienteAlcField;
            }
            set {
                if ((this.nuSaldoPendienteAlcField.Equals(value) != true)) {
                    this.nuSaldoPendienteAlcField = value;
                    this.RaisePropertyChanged("nuSaldoPendienteAlc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nuSaldoPendienteUltimaFactura {
            get {
                return this.nuSaldoPendienteUltimaFacturaField;
            }
            set {
                if ((this.nuSaldoPendienteUltimaFacturaField.Equals(value) != true)) {
                    this.nuSaldoPendienteUltimaFacturaField = value;
                    this.RaisePropertyChanged("nuSaldoPendienteUltimaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nuSaldoPteFinanciacion {
            get {
                return this.nuSaldoPteFinanciacionField;
            }
            set {
                if ((this.nuSaldoPteFinanciacionField.Equals(value) != true)) {
                    this.nuSaldoPteFinanciacionField = value;
                    this.RaisePropertyChanged("nuSaldoPteFinanciacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vaDireccion {
            get {
                return this.vaDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.vaDireccionField, value) != true)) {
                    this.vaDireccionField = value;
                    this.RaisePropertyChanged("vaDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vaNombre {
            get {
                return this.vaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.vaNombreField, value) != true)) {
                    this.vaNombreField = value;
                    this.RaisePropertyChanged("vaNombre");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioWebPQR")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuentaCobro))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuponPago))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosSuscriptor))]
    public partial class BaseRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeRespuestaErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeRespuestaOkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuestaError {
            get {
                return this.MensajeRespuestaErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaErrorField, value) != true)) {
                    this.MensajeRespuestaErrorField = value;
                    this.RaisePropertyChanged("MensajeRespuestaError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuestaOk {
            get {
                return this.MensajeRespuestaOkField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaOkField, value) != true)) {
                    this.MensajeRespuestaOkField = value;
                    this.RaisePropertyChanged("MensajeRespuestaOk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosCuentaCobro", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioWebPQR")]
    [System.SerializableAttribute()]
    public partial class DatosCuentaCobro : WPFTerminaldeServiciosPQR.ServiceReferencePQR.BaseRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime daFechaGeneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long nuIdCuentaCobroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nuIdDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nuIdMaquinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nuIdMunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nuIdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long nuIdSuscriptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nuIdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nuSaldoPendienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valortotalfacturadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime daFechaGeneracion {
            get {
                return this.daFechaGeneracionField;
            }
            set {
                if ((this.daFechaGeneracionField.Equals(value) != true)) {
                    this.daFechaGeneracionField = value;
                    this.RaisePropertyChanged("daFechaGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long nuIdCuentaCobro {
            get {
                return this.nuIdCuentaCobroField;
            }
            set {
                if ((this.nuIdCuentaCobroField.Equals(value) != true)) {
                    this.nuIdCuentaCobroField = value;
                    this.RaisePropertyChanged("nuIdCuentaCobro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nuIdDepartamento {
            get {
                return this.nuIdDepartamentoField;
            }
            set {
                if ((this.nuIdDepartamentoField.Equals(value) != true)) {
                    this.nuIdDepartamentoField = value;
                    this.RaisePropertyChanged("nuIdDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nuIdMaquina {
            get {
                return this.nuIdMaquinaField;
            }
            set {
                if ((object.ReferenceEquals(this.nuIdMaquinaField, value) != true)) {
                    this.nuIdMaquinaField = value;
                    this.RaisePropertyChanged("nuIdMaquina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nuIdMunicipio {
            get {
                return this.nuIdMunicipioField;
            }
            set {
                if ((this.nuIdMunicipioField.Equals(value) != true)) {
                    this.nuIdMunicipioField = value;
                    this.RaisePropertyChanged("nuIdMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nuIdPais {
            get {
                return this.nuIdPaisField;
            }
            set {
                if ((this.nuIdPaisField.Equals(value) != true)) {
                    this.nuIdPaisField = value;
                    this.RaisePropertyChanged("nuIdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long nuIdSuscriptor {
            get {
                return this.nuIdSuscriptorField;
            }
            set {
                if ((this.nuIdSuscriptorField.Equals(value) != true)) {
                    this.nuIdSuscriptorField = value;
                    this.RaisePropertyChanged("nuIdSuscriptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nuIdUsuario {
            get {
                return this.nuIdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nuIdUsuarioField, value) != true)) {
                    this.nuIdUsuarioField = value;
                    this.RaisePropertyChanged("nuIdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nuSaldoPendiente {
            get {
                return this.nuSaldoPendienteField;
            }
            set {
                if ((this.nuSaldoPendienteField.Equals(value) != true)) {
                    this.nuSaldoPendienteField = value;
                    this.RaisePropertyChanged("nuSaldoPendiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vaNombre {
            get {
                return this.vaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.vaNombreField, value) != true)) {
                    this.vaNombreField = value;
                    this.RaisePropertyChanged("vaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valortotalfacturado {
            get {
                return this.valortotalfacturadoField;
            }
            set {
                if ((this.valortotalfacturadoField.Equals(value) != true)) {
                    this.valortotalfacturadoField = value;
                    this.RaisePropertyChanged("valortotalfacturado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosCuponPago", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioWebPQR")]
    [System.SerializableAttribute()]
    public partial class DatosCuponPago : WPFTerminaldeServiciosPQR.ServiceReferencePQR.BaseRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime daFechaGeneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long nuIdCuentaCobroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long nuIdCuponPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nuIdDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nuIdEstadoCuponPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nuIdMaquinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nuIdMunicipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nuIdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long nuIdSuscriptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nuIdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nuSaldoPendienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nuValorCuponPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double saldoafavorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vaEstadoCuponPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vaTipoCuponPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valortotalfacturadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valortotalfacturadoglobalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime daFechaGeneracion {
            get {
                return this.daFechaGeneracionField;
            }
            set {
                if ((this.daFechaGeneracionField.Equals(value) != true)) {
                    this.daFechaGeneracionField = value;
                    this.RaisePropertyChanged("daFechaGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long nuIdCuentaCobro {
            get {
                return this.nuIdCuentaCobroField;
            }
            set {
                if ((this.nuIdCuentaCobroField.Equals(value) != true)) {
                    this.nuIdCuentaCobroField = value;
                    this.RaisePropertyChanged("nuIdCuentaCobro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long nuIdCuponPago {
            get {
                return this.nuIdCuponPagoField;
            }
            set {
                if ((this.nuIdCuponPagoField.Equals(value) != true)) {
                    this.nuIdCuponPagoField = value;
                    this.RaisePropertyChanged("nuIdCuponPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nuIdDepartamento {
            get {
                return this.nuIdDepartamentoField;
            }
            set {
                if ((this.nuIdDepartamentoField.Equals(value) != true)) {
                    this.nuIdDepartamentoField = value;
                    this.RaisePropertyChanged("nuIdDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nuIdEstadoCuponPago {
            get {
                return this.nuIdEstadoCuponPagoField;
            }
            set {
                if ((this.nuIdEstadoCuponPagoField.Equals(value) != true)) {
                    this.nuIdEstadoCuponPagoField = value;
                    this.RaisePropertyChanged("nuIdEstadoCuponPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nuIdMaquina {
            get {
                return this.nuIdMaquinaField;
            }
            set {
                if ((object.ReferenceEquals(this.nuIdMaquinaField, value) != true)) {
                    this.nuIdMaquinaField = value;
                    this.RaisePropertyChanged("nuIdMaquina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nuIdMunicipio {
            get {
                return this.nuIdMunicipioField;
            }
            set {
                if ((this.nuIdMunicipioField.Equals(value) != true)) {
                    this.nuIdMunicipioField = value;
                    this.RaisePropertyChanged("nuIdMunicipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nuIdPais {
            get {
                return this.nuIdPaisField;
            }
            set {
                if ((this.nuIdPaisField.Equals(value) != true)) {
                    this.nuIdPaisField = value;
                    this.RaisePropertyChanged("nuIdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long nuIdSuscriptor {
            get {
                return this.nuIdSuscriptorField;
            }
            set {
                if ((this.nuIdSuscriptorField.Equals(value) != true)) {
                    this.nuIdSuscriptorField = value;
                    this.RaisePropertyChanged("nuIdSuscriptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nuIdUsuario {
            get {
                return this.nuIdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nuIdUsuarioField, value) != true)) {
                    this.nuIdUsuarioField = value;
                    this.RaisePropertyChanged("nuIdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nuSaldoPendiente {
            get {
                return this.nuSaldoPendienteField;
            }
            set {
                if ((this.nuSaldoPendienteField.Equals(value) != true)) {
                    this.nuSaldoPendienteField = value;
                    this.RaisePropertyChanged("nuSaldoPendiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nuValorCuponPago {
            get {
                return this.nuValorCuponPagoField;
            }
            set {
                if ((this.nuValorCuponPagoField.Equals(value) != true)) {
                    this.nuValorCuponPagoField = value;
                    this.RaisePropertyChanged("nuValorCuponPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double saldoafavor {
            get {
                return this.saldoafavorField;
            }
            set {
                if ((this.saldoafavorField.Equals(value) != true)) {
                    this.saldoafavorField = value;
                    this.RaisePropertyChanged("saldoafavor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vaEstadoCuponPago {
            get {
                return this.vaEstadoCuponPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.vaEstadoCuponPagoField, value) != true)) {
                    this.vaEstadoCuponPagoField = value;
                    this.RaisePropertyChanged("vaEstadoCuponPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vaNombre {
            get {
                return this.vaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.vaNombreField, value) != true)) {
                    this.vaNombreField = value;
                    this.RaisePropertyChanged("vaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vaTipoCuponPago {
            get {
                return this.vaTipoCuponPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.vaTipoCuponPagoField, value) != true)) {
                    this.vaTipoCuponPagoField = value;
                    this.RaisePropertyChanged("vaTipoCuponPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valortotalfacturado {
            get {
                return this.valortotalfacturadoField;
            }
            set {
                if ((this.valortotalfacturadoField.Equals(value) != true)) {
                    this.valortotalfacturadoField = value;
                    this.RaisePropertyChanged("valortotalfacturado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valortotalfacturadoglobal {
            get {
                return this.valortotalfacturadoglobalField;
            }
            set {
                if ((this.valortotalfacturadoglobalField.Equals(value) != true)) {
                    this.valortotalfacturadoglobalField = value;
                    this.RaisePropertyChanged("valortotalfacturadoglobal");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePQR.IWSServicePQR")]
    public interface IWSServicePQR {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerDatosSuscriptor", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerDatosSuscriptorResponse")]
        WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosSuscriptor[] obtenerDatosSuscriptor(long nuIdsuscriptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerDatosSuscriptor", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerDatosSuscriptorResponse")]
        System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosSuscriptor[]> obtenerDatosSuscriptorAsync(long nuIdsuscriptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerSuscriptorPazySalvo", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerSuscriptorPazySalvoResponse")]
        WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosSuscriptor[] obtenerSuscriptorPazySalvo(long nuIdsuscriptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerSuscriptorPazySalvo", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerSuscriptorPazySalvoResponse")]
        System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosSuscriptor[]> obtenerSuscriptorPazySalvoAsync(long nuIdsuscriptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerDatosCuentaCobro", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerDatosCuentaCobroResponse")]
        WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuentaCobro[] obtenerDatosCuentaCobro(long nuIdsuscriptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerDatosCuentaCobro", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerDatosCuentaCobroResponse")]
        System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuentaCobro[]> obtenerDatosCuentaCobroAsync(long nuIdsuscriptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerDatosCuponPago", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerDatosCuponPagoResponse")]
        WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuponPago[] obtenerDatosCuponPago(long nuIdcuponpago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerDatosCuponPago", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerDatosCuponPagoResponse")]
        System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuponPago[]> obtenerDatosCuponPagoAsync(long nuIdcuponpago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerEstadoFacturacion", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerEstadoFacturacionResponse")]
        bool obtenerEstadoFacturacion(long nuIdcuponpago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/obtenerEstadoFacturacion", ReplyAction="http://tempuri.org/IWSServicePQR/obtenerEstadoFacturacionResponse")]
        System.Threading.Tasks.Task<bool> obtenerEstadoFacturacionAsync(long nuIdcuponpago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/generarDatosCuponPago", ReplyAction="http://tempuri.org/IWSServicePQR/generarDatosCuponPagoResponse")]
        WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuponPago[] generarDatosCuponPago(long nuIdSuscriptor, int nuValorCuponPago, long nuIdCuentaCobro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSServicePQR/generarDatosCuponPago", ReplyAction="http://tempuri.org/IWSServicePQR/generarDatosCuponPagoResponse")]
        System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuponPago[]> generarDatosCuponPagoAsync(long nuIdSuscriptor, int nuValorCuponPago, long nuIdCuentaCobro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSServicePQRChannel : WPFTerminaldeServiciosPQR.ServiceReferencePQR.IWSServicePQR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSServicePQRClient : System.ServiceModel.ClientBase<WPFTerminaldeServiciosPQR.ServiceReferencePQR.IWSServicePQR>, WPFTerminaldeServiciosPQR.ServiceReferencePQR.IWSServicePQR {
        
        public WSServicePQRClient() {
        }
        
        public WSServicePQRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSServicePQRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServicePQRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServicePQRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosSuscriptor[] obtenerDatosSuscriptor(long nuIdsuscriptor) {
            return base.Channel.obtenerDatosSuscriptor(nuIdsuscriptor);
        }
        
        public System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosSuscriptor[]> obtenerDatosSuscriptorAsync(long nuIdsuscriptor) {
            return base.Channel.obtenerDatosSuscriptorAsync(nuIdsuscriptor);
        }
        
        public WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosSuscriptor[] obtenerSuscriptorPazySalvo(long nuIdsuscriptor) {
            return base.Channel.obtenerSuscriptorPazySalvo(nuIdsuscriptor);
        }
        
        public System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosSuscriptor[]> obtenerSuscriptorPazySalvoAsync(long nuIdsuscriptor) {
            return base.Channel.obtenerSuscriptorPazySalvoAsync(nuIdsuscriptor);
        }
        
        public WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuentaCobro[] obtenerDatosCuentaCobro(long nuIdsuscriptor) {
            return base.Channel.obtenerDatosCuentaCobro(nuIdsuscriptor);
        }
        
        public System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuentaCobro[]> obtenerDatosCuentaCobroAsync(long nuIdsuscriptor) {
            return base.Channel.obtenerDatosCuentaCobroAsync(nuIdsuscriptor);
        }
        
        public WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuponPago[] obtenerDatosCuponPago(long nuIdcuponpago) {
            return base.Channel.obtenerDatosCuponPago(nuIdcuponpago);
        }
        
        public System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuponPago[]> obtenerDatosCuponPagoAsync(long nuIdcuponpago) {
            return base.Channel.obtenerDatosCuponPagoAsync(nuIdcuponpago);
        }
        
        public bool obtenerEstadoFacturacion(long nuIdcuponpago) {
            return base.Channel.obtenerEstadoFacturacion(nuIdcuponpago);
        }
        
        public System.Threading.Tasks.Task<bool> obtenerEstadoFacturacionAsync(long nuIdcuponpago) {
            return base.Channel.obtenerEstadoFacturacionAsync(nuIdcuponpago);
        }
        
        public WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuponPago[] generarDatosCuponPago(long nuIdSuscriptor, int nuValorCuponPago, long nuIdCuentaCobro) {
            return base.Channel.generarDatosCuponPago(nuIdSuscriptor, nuValorCuponPago, nuIdCuentaCobro);
        }
        
        public System.Threading.Tasks.Task<WPFTerminaldeServiciosPQR.ServiceReferencePQR.DatosCuponPago[]> generarDatosCuponPagoAsync(long nuIdSuscriptor, int nuValorCuponPago, long nuIdCuentaCobro) {
            return base.Channel.generarDatosCuponPagoAsync(nuIdSuscriptor, nuValorCuponPago, nuIdCuentaCobro);
        }
    }
}
